### PR TITLE
General improvements

### LINKED ISSUE #41: Serde base64 serialization
Is there a reason our implementation of `serde::Serialize` and `serde::Deserialize` are checking for `is_human_readable` and de/encode with base64 in that case? Otherwise I would propose to remove this completely.

### PR DESCRIPTION
**Pull request by daxpedda**
Lessons learned from novifinancial/opaque-ke#250.

Noteworthy:
- Fix `Debug` implementation.
- Fix de-serialization when using owned bytes, like with `bincode::deserialize_from` (see novifinancial/voprf#33).
- Replace macro with [derive-where](https://crates.io/crates/derive-where).
- Add [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) field.
- Add `Ord` and `PartialOrd` implementations for high-level types.
- Ability to test without the ristretto255 backend. Selecting any backend is still required.
- Removed base64 encoding and dependency for `is_human_readable` serializers for Serde.
- Only take references in all user-facing function signatures for types that aren't `Copy`.

Fixes #41.

### CODE REVIEW

**Review by kevinlewi — APPROVED** [review]
LGTM!

**Comment by kevinlewi** [comment]
@daxpedda, ping! Just wanted to check in and see if this is ready to take out of draft mode.

**Comment by daxpedda** [comment]
I got so frustrated with the macros that we were using that I started developing https://github.com/ModProg/derive-where.
Almost done, then I'm back to continuing here.

**Comment by daxpedda** [comment]
I fixed #41 along the way, removing the base64 dependency too.

**Pull request merged**
